name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Package Build ğŸª›
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm i -g yarn
      
      - name: Installing Packages ğŸ“
        run: yarn

      - name: Building Application ğŸ
        run: yarn package

      - run: |
          cd out
          cd */
          ls
